config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {
    sessions: 'frontend/sessions',
    passwords: 'frontend/passwords'
  }
  devise_for :admin, path: 'admin', controllers: {
    sessions: 'backend/sessions',
    passwords: 'backend/passwords'
  }

  scope :admin, as: :admin do
    scope module: :backend do
      root 'home#index'
      resources :admins, except: :show
      resources :products
      resources :categories
      resources :users
      resources :sliders
    end
  end

  scope module: :frontend do
    root 'home#index'
  end
end

app/models/slider.rb
class Slider < ApplicationRecord
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  enum status: [:inactive, :active ]
end

app/controllers/backend/admins_controller.rb
class Backend::AdminsController < Backend::BaseController
  authorize_resource

  before_action :find_admin, only: [:edit, :update, :destroy]

  def index
    @admins = Admin.order(created_at: :desc).page(params[:page]).per(10)
    @breadcrumbs = {t('view.admins.admins') => admin_admins_path, t('view.layout.list') => nil}
  end

  def new
    @breadcrumbs = {t('view.admins.admins') => admin_admins_path, t('view.button.new') => nil}
    @admin = Admin.new
  end

  def create
    @admin = Admin.new admin_params
    if @admin.save
      respond_to do |format|
        format.html {redirect_to admin_admins_path, notice: t('view.messages.created_success', model_name: t('view.admins.model_name'))}
      end
    else
      @breadcrumbs = {t('view.admins.admins') => admin_admins_path, t('view.button.new') => nil}
      render :new
    end
  end

  def edit
    @breadcrumbs = {t('view.admins.admins') => admin_admins_path, t('view.button.edit') => nil}
  end

  def update
    if @admin.update_attributes admin_params
      respond_to do |format|
        format.html {redirect_to admin_admins_path, notice: t('view.messages.updated_success', model_name: t('view.admins.model_name'))}
      end
    else
      @breadcrumbs = {t('view.admins.admins') => admin_admins_path, t('view.button.edit') => nil}
      render :edit
    end
  end

  def destroy
    if @admin.destroy
      flash[:success] = t('view.messages.deleted_success', model_name: t('view.admins.model_name'))
    else
      flash[:danger] = @admin.errors.full_messages
    end

    redirect_to admin_admins_path
  end

  private

  def find_admin
    @admin = Admin.find_by_id params[:id]
    redirect_to admin_admins_path, flash: {danger: t('view.messages.not_found', model_name: t('view.admins.model_name'))} unless @admin
  end

  def admin_params
    if params[:admin][:password].blank?
      params.require(:admin).permit :email
    else
      params.require(:admin).permit :email, :password, :password_confirmation
    end
  end
end

app/controllers/backend/base_controller.rb
class Backend::BaseController < ApplicationController
  layout 'backend'

  before_action :authenticate_admin!

  check_authorization :unless => :devise_controller?

  def current_ability
    @current_ability ||= AdminAbility.new current_admin
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to admin_root_url, :alert => exception.message
  end
end

app/controllers/backend/categories_controller.rb
class Backend::CategoriesController < Backend::BaseController
  authorize_resource
  before_action :find_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.active.page(params[:page]).per(30)
    @breadcrumbs = {'categories' => admin_categories_path, t('view.layout.list') => nil}
  end

  def new
    @breadcrumbs = {'categories' => admin_products_path, t('view.button.new') => nil}
    @category = Category.new
    @categories = Category.parent_categories.active
  end

  def create
    @categories = Category.new category_params
    if @categories.save
      respond_to do |format|
        format.html {redirect_to admin_categories_path, notice: t('view.messages.created_success', model_name: 'Category')}
      end
    else
      @breadcrumbs = {t('view.managers.managers') => admin_categories_path, t('view.button.new') => nil}
      render :new
    end
  end

  def edit
    @breadcrumbs = {'categories' => admin_categories_path, t('view.button.edit') => nil}
    @categories = Category.parent_categories.active
  end

  def update
    if @category.update_attributes category_params
      respond_to do |format|
        format.html {redirect_to admin_categories_path, notice: t('view.messages.updated_success', model_name: 'Category')}
      end
    else
      @breadcrumbs = {'categories' => admin_categories_path, t('view.button.edit') => nil}
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t('view.messages.deleted_success', model_name: 'Category')
    else
      flash[:danger] = @category.errors.full_messages
    end

    redirect_to admin_categories_path
  end

  private

  def find_category
    @category = Category.find_by_id params[:id]
    redirect_to admin_categories_path, flash: {danger: t('view.messages.not_found')} unless @category
  end
  def category_params
    params.require(:category).permit :name, :status, :parent_id
  end
end

app/controllers/backend/home_controller.rb
class Backend::HomeController < Backend::BaseController
  skip_authorization_check only: :index

  def index
    @breadcrumbs = {}
  end
end

app/controllers/backend/passwords_controller.rb
class Backend::PasswordsController < Devise::PasswordsController
  layout 'devise'
end

app/controllers/backend/products_controller.rb
class Backend::ProductsController < Backend::BaseController
  authorize_resource
  before_action :find_product, only: [:edit, :update, :destroy]

  def index
    @products = Product.active.page(params[:page]).per(30)
    @breadcrumbs = {'list_products' => admin_products_path, t('view.layout.list') => nil}
  end

  def new
    @breadcrumbs = {'list_products' => admin_products_path, t('view.button.new') => nil}
    @categories = Category.active.child_categories
    @product = Product.new
    4.times do 
      @product.product_images.build
    end
  end

  def edit
    @breadcrumbs = {'list_products' => admin_products_path, t('view.button.edit') => nil}
    @categories = Category.active
    @product.product_images.build unless @product.product_images.present?
  end

  def create
    @product = Product.new product_params
    if @product.save
      respond_to do |format|
        format.html {redirect_to admin_products_path, notice: t('view.messages.created_success', model_name: 'Product')}
      end
    else
      @breadcrumbs = {t('view.managers.managers') => admin_products_path, t('view.button.new') => nil}
      render :new
    end
  end

  def update
    if @product.update_attributes product_params
      respond_to do |format|
        format.html {redirect_to admin_products_path, notice: t('view.messages.updated_success', model_name: 'Product')}
      end
    else
      @breadcrumbs = {'list_products' => admin_products_path, t('view.button.edit') => nil}
      render :edit
    end
  end

  def destroy
    if @product.destroy
      flash[:success] = t('view.messages.deleted_success', model_name: 'Product')
    else
      flash[:danger] = @product.errors.full_messages
    end

    redirect_to admin_products_path
  end

  private

  def find_product
    @product = Product.find_by_id params[:id]
    redirect_to admin_products_path, flash: {danger: t('view.messages.not_found')} unless @product
  end
  def product_params
    params.require(:product).permit :name, :price, :note, :sale, :description, :category_id, :status, :image, :short_desc,
                                    product_images_attributes: [:id, :picture, :product_id]
  end
end

app/controllers/backend/sessions_controller.rb
class Backend::SessionsController < Devise::SessionsController
  layout 'devise'
end

app/controllers/backend/sliders_controller.rb
class Backend::SlidersController < Backend::BaseController
  authorize_resource
  before_action :find_slider, only: [:edit, :update, :destroy]

  def index
    @sliders = Slider.page(params[:page]).per(30)
    @breadcrumbs = {'Sliders' => admin_sliders_path, t('view.layout.list') => nil}
  end

  def new
    @breadcrumbs = {'Sliders' => admin_sliders_path, t('view.button.new') => nil}
    @slider = Slider.new
  end

  def edit
    @breadcrumbs = {'Sliders' => admin_sliders_path, t('view.button.edit') => nil}
  end

  def create
    @slider = Slider.new slider_params
    if @slider.save
      respond_to do |format|
        format.html {redirect_to admin_sliders_path, notice: t('view.messages.created_success', model_name: 'Slider')}
      end
    else
      @breadcrumbs = {"Slider" => admin_sliders_path, t('view.button.new') => nil}
      render :new
    end
  end

  def update
    if @slider.update_attributes slider_params
      respond_to do |format|
        format.html {redirect_to admin_sliders_path, notice: t('view.messages.updated_success', model_name: 'Slider')}
      end
    else
      @breadcrumbs = {'Slider' => admin_sliders_path, t('view.button.edit') => nil}
      render :edit
    end
  end

  def destroy
    if @slider.destroy
      flash[:success] = t('view.messages.deleted_success', model_name: 'Slider')
    else
      flash[:danger] = @slider.errors.full_messages
    end

    redirect_to admin_sliders_path
  end

  private

  def find_slider
    @slider = Slider.find_by_id params[:id]
    redirect_to admin_sliders_path, flash: {danger: t('view.messages.not_found')} unless @slider
  end
  def slider_params
    params.require(:slider).permit :image, :status
  end
end

app/controllers/backend/users_controller.rb
class Backend::UsersController < Backend::BaseController
  authorize_resource
  before_action :find_user, only: [:edit, :update, :destroy]

  def index
    @users = User.includes(:profile).page(params[:page]).per(30)
    @breadcrumbs = {'users' => admin_users_path, t('view.layout.list') => nil}
  end

  # def new
  #   @breadcrumbs = {'categories' => admin_products_path, t('view.button.new') => nil}
  #   @user = User.new
  # end
  #
  # def create
  #   @categories = Category.new category_params
  #   if @categories.save
  #     respond_to do |format|
  #       format.html {redirect_to admin_categories_path, notice: t('view.messages.created_success', model_name: 'Category')}
  #     end
  #   else
  #     @breadcrumbs = {t('view.managers.managers') => admin_categories_path, t('view.button.new') => nil}
  #     render :new
  #   end
  # end
  #
  # def edit
  #   @breadcrumbs = {'categories' => admin_categories_path, t('view.button.edit') => nil}
  # end
  #
  # def update
  #   if @category.update_attributes category_params
  #     respond_to do |format|
  #       format.html {redirect_to admin_categories_path, notice: t('view.messages.updated_success', model_name: 'Category')}
  #     end
  #   else
  #     @breadcrumbs = {'categories' => admin_categories_path, t('view.button.edit') => nil}
  #     render :edit
  #   end
  # end

  def destroy
    if @user.destroy
      flash[:success] = t('view.messages.deleted_success', model_name: 'User')
    else
      flash[:danger] = @user.errors.full_messages
    end

    redirect_to admin_users_path
  end

  private

  def find_user
    @user = User.find_by_id params[:id]
    redirect_to admin_users_path, flash: {danger: t('view.messages.not_found')} unless @user
  end
  def user_params
    params.require(:category).permit :name, :status
  end
end

app/views/backend/sliders/_form.html.erb
<%= form_for [:admin, slider], html: {class: 'form-horizontal', autocomplete: 'off'} do |f| %>
  <div class="box-body col-md-8">
    <div class="form-group">
      <label class="col-md-3">
        Name
        <span class="required-star">*</span>
      </label>
      <div class="col-md-9">
        <%= f.file_field :image %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-3">
        Status
        <span class="required-star">*</span>
      </label>
      <div class="col-md-9">
        <%= f.select :status, Slider.statuses.keys.to_a, {}, class: "form-control" %>
      </div>
    </div>

  </div>

  <div class="box-footer">
    <div class="col-md-8">
      <%= f.submit t('view.button.save'), class: 'btn btn-primary col-md-offset-3' %>
    </div>
  </div>
  <div class="clearfix"></div>
<% end %>

app/views/backend/sliders/edit.html.erb
<% provide :title, t('view.managers.edit_manager') %>

<section class="content">
  <div class="box" id="edit-manager">
    <h1 class="col-md-12 page-header"><%= t('view.managers.edit_manager') %></h1>

    <%= render partial: 'form', locals: {product: @product, categories: @categories} %>
  </div>
  <div class="clearfix"></div>
</section>

app/views/backend/sliders/index.html.erb
<%= render partial: 'backend/shared/alert' %>
<div class="clearfix"></div>

<section class="content listing-wrapper" id="admin-listing">
  <div class="box">
    <div class="col-md-12 page-header">
      <h3 class="pull-left">List Sliders</h3>
      <div class="pull-right">
        <% if can? :create, Slider %>
          <%= link_to t('view.button.new'), new_admin_slider_path, class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="box-body">
      <table class="table table-bordered listing-table">
        <thead>
        <tr>
          <th class="col-md-1"><%= t('view.admins.id') %></th>
          <th>Image</th>
          <th>Status</th>
          <th class="col-md-2"><%= t('view.layout.action') %></th>
        </tr>
        </thead>
        <tbody>
        <% @sliders.each do |slider| %>
          <tr>
            <td><%= slider.id %></td>
            <td></td>
            <td><%= slider.status %></td>
            <td>
              <% if can? :update, Slider %>
                <a href="<%= edit_admin_slider_path(slider) %>" class="action-icon btn btn-info">
                  <%= t('view.button.edit') %>
                </a>
              <% end %>
              <% if can? :destroy, Admin %>
                <a href="#modal-delete" data-toggle="modal" data-url="/admin/admins/<%= slider.id %>"
                   class="action-icon remove btn btn-danger">
                  <%= t('view.button.delete') %>
                </a>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>

      <div class="text-center">
        <%= paginate @sliders %>
      </div>
    </div>
  </div>
</section>
<div class="clearfix"></div>

<%= render partial: 'backend/shared/delete', locals: {model_name: 'Slider'} %>

app/views/backend/sliders/new.html.erb
<% provide :title, 'New Slider' %>

<section class="content">
  <div class="box" id="new-manager">
    <h1 class="col-md-12 page-header">New slider</h1>

    <%= render partial: 'form', locals: {slider: @slider} %>
  </div>
  <div class="clearfix"></div>
</section>